import type { NextPage } from 'next'
import Head from 'next/head'
import dynamic from 'next/dynamic';
import { useMemo } from 'react';

const Map = dynamic(() => import("./components/Map"), { loading: () => <div>Loading</div>, ssr: false });

// TODO: get loader animation

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-full">
        <Map />
      </main>

      <footer>
      </footer>
    </>
  )
}

export default Home
